language: go

services:
  - redis-server

go:
  - "1.10"
  - 1.11
  - tip

script:
  - go get github.com/mattn/goveralls
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken Z9zWraoQqoHbtjUD0qIatjhgmwGM40zOO